### ISSUE TITLE
Added to new theme server

### ISSUE THREAD

**Issue by thomasdavis** [XuluWarrior/jsonresume-theme-kards#4]
I've added kards as an official theme -> https://themes.jsonresume.org/theme/kards

Great job

**Comment by XuluWarrior** [comment]
@thomasdavis Thanks for the add.

I'm trying to get a feel for how the new infrastructure will work.  Will available themes be discoverable?
The old themes.jsonresume.org had a list of themes with a preview.  Are you planning something similar?

There is also https://jsonresume.org/themes/ but I don't know the last time that page was updated.

If themes are updated will they automatically be updated on the website?

**Comment by thomasdavis** [comment]
There is no list of themes yet, I will expose the endpoint again. 

I just whitelist themes now and have to manually update what is available on the registry.
